# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-29 10:04
from __future__ import unicode_literals

from django.db import migrations
import django_prices.models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20180108_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=django_prices.models.PriceField(currency='INR', decimal_places=2, default=0, max_digits=12),
        ),
    ]
